config/routes.rb
WeSay::Application.routes.draw do
  
  root to: 'base#home'

  get 'about', to: 'base#about', as: 'about'

  devise_for :users

  resources :webs do
    resources :pages, controller: 'webs/pages'
  end

  

  

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :web
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :webs
end

app/models/web.rb
class Web < ActiveRecord::Base
  belongs_to :user
  has_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/webs/pages_controller.rb
class Webs::PagesController < ApplicationController
  before_action :set_web
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = @web.pages.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web
      @web = Web.find(params[:web_id])
    end


    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:web_id, :title, :body)
    end
end

app/controllers/webs_controller.rb
class WebsController < ApplicationController
  before_action :set_web, only: [:show, :edit, :update, :destroy]

  # GET /webs
  # GET /webs.json
  def index
    @webs = Web.all
  end

  # GET /webs/1
  # GET /webs/1.json
  def show
  end

  # GET /webs/new
  def new
    @controller_name = controller_name
    @web = Web.new
  end

  # GET /webs/1/edit
  def edit
  end

  # POST /webs
  # POST /webs.json
  def create
    @web = Web.new(web_params)

    respond_to do |format|
      if @web.save
        format.html { redirect_to @web, notice: 'Web was successfully created.' }
        format.json { render action: 'show', status: :created, location: @web }
      else
        format.html { render action: 'new' }
        format.json { render json: @web.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webs/1
  # PATCH/PUT /webs/1.json
  def update
    respond_to do |format|
      if @web.update(web_params)
        format.html { redirect_to @web, notice: 'Web was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webs/1
  # DELETE /webs/1.json
  def destroy
    @web.destroy
    respond_to do |format|
      format.html { redirect_to webs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web
      @web = Web.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def web_params
      params.require(:web).permit(:user_id, :title, :description, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation
    if lookup_context.exists?("nav", params[:controller], true)
      {partial: 'nav'}
    else
      {partial: 'layouts/nav'}
    end
  end

  def markdown
      options = {autolink: true, no_intra_emphasis: true, fenced_code_blocks: true}
      markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options )
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/webs_helper.rb
module WebsHelper
end

app/views/base/about.html.erb
<header>
  <h1>About</h1>
</header>
<p>This is an app built by Xander Miller as part of his Bloc.io course. I home you find it shiny!</p>

app/views/base/home.html.erb
<header>
  <h1>We Say!</h1>
</header>
<p>This should appear as the root page now that is routed correctly.</p>

app/views/layouts/_crumb.html.erb
<nav id='crumb'>
  <ul>
    <li><%= link_to 'User', '#' %></li>    
    <%= yield :crumb %>
  </ul>
</nav>

app/views/layouts/_nav.html.erb
<nav id='main-nav'>
  <h2 id='logo'>We Say!</h2>
  <ul>
    <li><%= link_to 'Home', root_path %></li>    
    <li><%= link_to 'Webs', webs_path %></li>
    <%= yield :nav %>
    <li><%= link_to 'About', about_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>WeSay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class='container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="three columns sidebar">
        <%= render navigation %>
      </div>
      <div class="twelve columns offset-by-one"
        <%= render partial: 'layouts/crumb' %>
        <%= yield %>
      </div>
    </div>
</body>

</html>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Web:</strong>
  <%= @page.web %>
</p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/webs/_form.html.erb
<%= form_for(@web) do |f| %>
  <% if @web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web.errors.count, "error") %> prohibited this web from being saved:</h2>

      <ul>
      <% @web.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webs/_web.html.erb
<article class='web'>
  <header>
    <nav class='web-nav'>
      <ul>
        <li><%= link_to 'Show', web %></li>
        <li><%= link_to 'Edit', edit_web_path(web) %></li>
        <li><%= link_to 'Destroy', web, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </nav>
    <h1><%= web.title %></h1>
    <small><%= web.user %></small>
  </header>
  <p><%= web.description %></p>

</article>

app/views/webs/edit.html.erb
<h1>Editing web</h1>

<%= render 'form' %>

<%= link_to 'Show', @web %> |
<%= link_to 'Back', webs_path %>

app/views/webs/index.html.erb
<header>
  <h1>Your Webs</h1>
</header>

<%= render partial: 'web', collection: @webs %>

<br>

<%= link_to 'New Web', new_web_path %>

app/views/webs/new.html.erb
<h1>New web</h1>

<%= render 'form' %>

<%= link_to 'Back', webs_path %>

app/views/webs/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webs/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/webs/pages/index.html.erb
<% content_for :nav do %>
  <li><%= link_to 'Pages', web_pages_path(@web) %></li>
<% end %>

<% content_for :crumb do %>
  <li>/ Web: <%= link_to @web.title, @web %></li>
<% end %>

<header>
  <h1><%= "#{@web.id}  #{@web.title}" %></h1>
</header>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.body[0..175] %></td>
        <td><%= link_to 'Show', [@web, page] %></td>
        <!--
          <td>< link_to 'Edit', edit_page_path(page) %></td>
          <td>< link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
  < link_to 'New Page', new_page_path %>
-->

app/views/webs/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/webs/pages/show.html.erb
<% content_for :nav do %>
  <li><%= link_to 'Pages', web_pages_path(@web) %></li>
<% end %>

<% content_for :crumb do %>
  <li>/ Web: <%= link_to @web.title, @web %></li>
  <li>/ Page: <%= link_to @page.title, [@web, @page] %></li>
<% end %>


<%= raw markdown.render(@page.body) %>
<!--
< link_to 'Edit', edit_page_path(@page) %> |
< link_to 'Back', pages_path %>
-->

app/views/webs/show.html.erb
<% content_for :nav do %>
  <li><%= link_to 'Pages', web_pages_path(@web) %></li>
<% end %>

<% content_for :crumb do %>
  <li>/ Web: <%= link_to @web.title, @web %></li>
<% end %>

<header>
  <h1><%= "#{@web.id}  #{@web.title}" %></h1>
</header>

<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @web.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @web.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @web.description %>
</p>

<p>
  <strong>Private:</strong>
  <%= @web.private %>
</p>

<%= link_to 'Edit', edit_web_path(@web) %> |
<%= link_to 'Back', webs_path %>